apiVersion: v1
description: Catalog Enricher Service
name: catalog-enricher-service
version: 0.0.1
dependencies:
- name: qe-quarkus-app
  version: 0.0.1
  repository: http://quarkus-qe.github.io/helm-charts-parent
